// Os ids validos do banco de perguntas, para o POST /api/respostas recusar
// pergunta inventada.
//
// GOTCHA: e uma COPIA dos ids de client/src/data/questions.json, pelo mesmo
// motivo de _versao.js (as Functions nao importam do client). Aqui a sincronia
// nao e so manual: client/src/lib/sincronia.test.js compara as duas listas, e
// teste vermelho impede o build.
export const IDS_PERGUNTAS = new Set([
  "econ-renda-igual",
  "econ-propriedade-privada",
  "econ-estado-provedor",
  "econ-incentivo-esforco",
  "econ-taxar-ricos",
  "econ-responsabilidade-propria",
  "econ-seguro-desemprego",
  "econ-competicao",
  "auth-liberdade-expressao",
  "auth-lider-forte",
  "auth-direitos-civis",
  "auth-policia-ordem",
  "auth-protesto",
  "auth-obedecer",
  "auth-participacao",
  "auth-imprensa-crise",
  "front-imigracao-beneficio",
  "front-limites-imigracao",
  "front-cultura-enriquece",
  "front-apoiar-pais-errado",
  "front-cidadao-mundo",
  "front-proteger-economia",
  "front-acordos-internacionais",
  "front-interesse-nacional",
  "cost-identidade-genero",
  "cost-religiao-ciencia",
  "cost-aborto-acesso",
  "cost-mae-trabalha",
  "cost-educacao-sexual",
  "cost-lideres-homens",
  "cost-contraceptivos",
  "cost-obediencia-crianca",
  "eco-prioridade-ambiente",
  "eco-prioridade-crescimento",
  "eco-responsabilidade-clima",
  "eco-tecnologia-resolve",
  "eco-limites-planeta",
  "eco-gravidade-exagerada",
  "eco-natureza-fragil",
  "eco-recursos-para-uso",
  "povo-evidencia-cientifica",
  "povo-decisoes-diretas",
  "povo-especialistas-decidem",
  "povo-confio-pessoas-comuns",
  "povo-julgamento-lideres",
  "povo-elites-corruptas",
  "povo-freios-institucionais",
  "povo-politicos-distantes",
]);
